newjersey/dol-mcnj-main

backend/data/program-credentials/merge-credentials.py
Summary
=======
As prep work for some algorithm improvements to labeling the
credential type for each program, this pulls out the credential
type labeling code into its own function that operates per
dataframe row using the apply method. This will hopefully also
improve readability of which labels trump others when multiple
matches are possible through using early returns.
This refactor should not change the existing results.
Test Plan
=========
I ran the merge-credentials step on the base branch to get a baseline of the existing merged file and saved that a copy of that file. Then I ran merge-credentials for this branch and compared the two files using diff, ensuring there was no change to output caused by this refactor.
=> refactor: pull out credential type label function

backend/data/program-credentials/merge-credentials.py
Summary
=======
1. Add missing support for A.A. degrees when searching official names
2. Refactor to use enum for labeling credential types
Test Plan
=========
Compared output for merged file to base branch output and confirmed only changes were inclusion of A.A. programs.
=> fix: support aa degrees for credential type

backend/data/program-credentials/merge-credentials.py
Summary
=========
Until credential engine supports these additional credential types
we are going to treat them as certificates of completion when
labeling the credential engine type.
Test Plan
=========
Compared the changed output for the merge file to see that ESL and Pre-Apprenticeship labels have changed to Certificate of Completion labels.
=> feat: output esl and preapprenticeship as certificateofcompletion

backend/data/program-credentials/merge-credentials.py
Summary
========
As prework for a followup PR, this brings in the provider information into the dataframe used for doing credential type labeling.
As of right now, this should not change any of the output, and I wanted to do this as it's own PR to prove that it doesn't alter output. But a later followup PR will start using this provider infromation as part of the criteria for labeling some credential types (namely, degree credential types).
Test Plan
=========
Ran the etpl_table_seed_guide steps up through the merge-credentials script step for both the base commit and this branch and confirmed that there is no change to output.
=> refactor: enable using provider info for credential type labeling

backend/data/program-credentials/merge-credentials.py
Summary
=======
By combining both the degree awarded information along with the provider typeid, we can capture more of the Degree credentials without additional false postives, based on some data analysis of the current dataset.
When looking at the existing dataset, if the degree awarded indicated a specific degree type (Assocaite, Bachelor, Master, Doctoral) AND the TYPEID for the provider was either a 3 or a 4, the program appeared to be a program for that degree type. But if the TYPEID was anything else, then the program did not appear to be a degree program itself.
Test Plan
========
Ran this new version of merge-credentials and compared the output with prior runs. I looked at a sample of the changed program lines and confirmed that those programs were indeed being changed to the …
=> feat: match degree by degree awarded

backend/data/program-credentials/merge-credentials.py
Summary
=========
To make it easier for downstream systems to match up the CredentialType with the Credential Engine field, this changes the value of the CredentialType column to match the name of the type as defined in Credential Engine.
Test Plan
=========
Ran though the merge-credentials script and confirmed changed output for Credential Types
=> fix: match credential engine names

.circleci/config.yml
Summary
========
To support PR workflows and test incoming dependabot changes, we can configure CircleCI to run just the build and test part of the workflow on branches, leaving the deploys to only run off of main.
Test Plan
=======
This branch / PR serves as its own test as it should have a passing build and test status check from Circle CI
=> feat: run ci builds on branches

backend/data/transform-for-migration.py, etpl_table_seed_guide.md
Summary
=======
The system importing the etpl data for migration into Credential Engine cannot support importing csv files with linefeeds within the individual record columns. They have asked us to replace the internal linefeed characters with the token `<LF>` and then they will replace this after the import back with the line feeds.
Test Plan
========
- Did a spot check on the file to ensure that the line feeds were replaced with `<LF>` instead.
=> feat: provide modified file for data migration without inner record line feeds

.github/dependabot.yml, backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
Summary
=========
- Updates the @types/node package to match the current node major
version (16)
- Update @types/express to fix type issue with @types/node
- configures dependabot to not update major version of @types/nodes as
we want this to match the node version.
Test Plan
=======
- CI run passing, these are type information updates only and only impacts typescript compilation steps
=> chore: update @types/node to match node major version 16

backend/package-lock.json, backend/package.json
Summary
=======
Replaces the dependabot PR for upgrading wiremock, with an overrides version added for a dependency of wiremock. 
Short of it is that the sub dependency `npm-java-runner` had been pulling in a `path` npm package that was causing issues with `good-fences`. That was fixed in a PR I made to npm-java-runner and has been released, but until there is a new release of the main wiremock service, the node wrapper for it won't have a release that pulls in the latest npm-java-runner version. The `overrides` works around that by forcing version resolution to the latest line of npm-java-runner.
See https://github.com/tomasbjerre/npm-java-runner/issues/1 for more background on the good-fences and npm-java-runner issue.
Test
======
Feature tests pass in CI.
=> chore(deps-dev): bump wiremock from 2.27.1 to 2.33.2 in /backend

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
Summary
=======
Resolves the dependabot PR and ensures that both the frontend and backend are on the same typescript version.
Test Plan
=======
CI Passes.
=> chore(deps): bump typescript from 4.7.4 to 4.8.2

frontend/package.json
Simple "hack" to prevent accidental `yarn install`. Engine Yarn will not be able to find the Yarn version number `please-use-npm` and will halt the installation.
Prevents developers with `yarn` muscle memory from making a mess of the project.
_We could also further strengthen versions by specifying npm. But npm crossed a major version release with a minor Node release (Node 16.0.0 ships with npm 7.10.0, Node 16.11.0 shipped with npm 8.0.0)._
Will fail on `yarn` / `yarn install`.
=> chore(deps-dev): block accidental use of yarn

backend/data/csvInserter.js, backend/data/csvUpdater.js
Summary
========
There was an error in how the first single quote for data being pulled into the data tables was being handled. It was converting the first single quote into a double quotation mark, instead of the normal process of converting the single quotes into two single quotes for sql string escaping.
Found this via a security alert detected in #457 
Test Plan
=======
1. Created a empty file to use to create test migration files
```shell
head -n 1 backend/data/in_demand_cips.csv > backend/data/empty.csv
```
2. Created some test update migrations
```shell
./backend/data/create_update_migrations.sh empty.csv in_demand_cips.csv indemandcips backend/migrations/sqls/upFileName.sql backend/migrations/sqls/downFileName.sql
```
3. Check that the first entry with a single quotes is now …
=> fix: first single quote escape for fixtured data

backend/data/transform-for-migration.py
Summary
=======
Looking at examples within Credential Registry, line feeds are represented inside of string fields like description using escaped versions of CRLF (`"\r\n"`). We can use this as our line feed token to support the data migration effort.
Test Plan
=========
Ran the `transform-for-migration.py` script and checked the difference to ensure that the string literal `\r\n` was being printed where they were line feeds before.
=> fix: encode internal line feeds for data migration

scripts/feature-tests.sh
Summary
========
When running feature tests in CircleCI, the migration scripts running on a clean database result in around 300MBs of logged output because db-migrate logs all the data from the sql files. This makes it impractical to review failed test output on CircleCI failures.
This redirects the output of starting up the local prod server during feature tests to the null device to swallow the migration logs.
Test Plan
=======
Check the artifacts of the build-and-test job in circleci. feature-test-output.txt should now be readable / renderable in the browser and measured in KBs instead of hundreds of MBs.
Usefully, [the first run of this failed](https://app.circleci.com/pipelines/github/newjersey/d4ad/1524/workflows/e5cf6818-34f7-47bc-9c40-46ee350bc706/jobs/1595) and was able to verify …
=> chore: reduce logging during feature tests

.github/workflows/dependabot-auto-approve-and-merge.yml
Enables automatically approving and merging any dependabot PRs that are not for a major version upgrade. Auto merge will only merge if required status checks are all passing.
=> chore: enable automerge of passing dependabot PRs for patch and minor

.github/workflows/dependabot-auto-approve-and-merge.yml
Simple change to merge with rebase instead of a merge commit when doing the auto merge from dependabot PRs.
=> chore: use rebase for auto merges from dependabot

backend/src/domain/training/Program.ts, backend/src/domain/training/findTrainingsBy.test.ts, backend/src/domain/training/findTrainingsBy.ts
Summary
=======
There are a few programs which have null descriptions within the original data. When search results included these programs, the search would error due to the backend data transformation code assuming that the description would always be a string.
Example Error:
When visiting: https://training.njcareers.org/search/trade%20worker
Got:
This change allows for handling null program descriptions such as those cause by training 47189, and triggered by searches like `worker`.
Test Plan
=======
Ran the search `trade worker` on local environment, and confirmed that search results worked (This search fails on current prod version). 
Clicked on the entry for Hvacr and ensure the page loaded.
=> fix: handle null descriptions in search

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx
Summary
======
Switches from using napa for pulling in njwds to using the new npmjs package from [@newjersey/njwds](https://www.npmjs.com/package/@newjersey/njwds)
Test Plan
========
All test passed and UI looks normally when running locally (buttons style comes from njwds)
=> chore: use njwds from npmjs

frontend/src/components/Header.tsx, frontend/src/locales/en.ts, frontend/src/locales/es.ts
Fixed bug in which mobile menu options were significantly different than desktop menu options: missing links, items out of order. Changed "Counseling" link text to align with both, in both EN and ES.
* https://fearless.jira.com/browse/NJWE-78
* Verify code doesn't throw lint errors
* Perform visual comparison between desktop and mobile components to ensure all options and their links align.
=> UI Improvements: Fixed mobile menu options to match desktop nav options (NJWE-78)

README.md, frontend/src/index.tsx
Implements simple password auth based on environment variable `DEV_PASS` if environment is running in CI and not in production
* https://fearless.jira.com/jira/software/projects/NJWE/boards/114?selectedIssue=NJWE-223
* 
* Verify that password mechanism does not appear and site renders correctly in local dev environment
* Verify code doesn't throw test or lint errors errors
* Verify that password mechanism works in dev environment in CI
* Verify that password mechanism does not appear an site renders correctly in prod environment in CI
=> NJWE-223: Implement simple password auth for Training Explorer dev site

backend/src/domain/training/findTrainingsBy.ts, backend/src/fence.json
This PR removes an unused var from `findTrainingsBy.ts`. While we should consider having the option to kill API calls it is currently not implemented. I'm also not sure CE is robust enough for that type of functionality and hopefully the communication speed between our front and back ends is fast enough to not warrant one.
This PR also adds the `dotenv` package to good fences so we can use environment variables from within expressjs on GCP.
=> V2 Minor Edits

backend/src/domain/search/searchTrainings.ts, frontend/src/components/InDemandTag.tsx, frontend/src/locales/en.ts, frontend/src/locales/es.ts, frontend/src/search-results/TrainingResultCard.tsx
From @andrealuft:
`Woohoo! way to go Chelsea getting those by county in demand labels on there!
3 things:
I think we should remove the "tuition assistance may be available" for now. (I think it does make the tags too long and whatever we choose to do should also be on the non county specific tags).
The county specific tags should only be on trainings located in the counties where that occupation is in-demand or online trainings.
A lot of trainings are getting two regular in-demand tags or one reg in-demand tag and one country specific tag....`
=> Local exceptions refinement

backend/app.yaml.sh
Updated the app.yaml configuration to include a domain redirection rule that carries over sub-URLs for 'training.njcareers.org'. Now, requests like 'https://training.njcareers.org/training/37332' will correctly redirect to 'https://mycareer.nj.gov/training/37332' while preserving the sub-URL path.
=> feat: Enable sub-URL redirection in app.yaml

frontend/src/App.tsx
Move LandingPageCounselor and LandingPageExplorer routes under '/training' to streamline navigation. This change organizes counselor and explorer landing pages into the training section, improving the overall routing structure and making the URLs more intuitive for users navigating training-related content.
=> Refactor routing for LandingPageCounselor and LandingPageExplorer

frontend/src/styles/components/_introBlocks.scss
=> 1293 - Make homepage tool buttons focused on tab

frontend/src/search-results/SearchResultsPage.tsx
Resolves [1433](https://fearless.jira.com/jira/software/projects/NJWE/boards/114/backlog?assignee=712020%3A7f5e8498-eeba-4ef6-b44a-4185883e207e&selectedIssue=NJWE-1433)
Currently, the Advanced Search page for Training Explorer shows having a <title> element of Search results for "undefined". Changed to Advanced Search | Training Explorer | New Jersey Career Central for the sake of UX and tracking.
=> 1433: <title> element for TE advanced search page is `Search results for "undefined"`

frontend/src/search-results/SearchResultsPage.tsx
Resolves [1510](https://fearless.jira.com/jira/software/projects/NJWE/boards/114?assignee=712020%3A7f5e8498-eeba-4ef6-b44a-4185883e207e&selectedIssue=NJWE-1510)
Follow up to [1433](https://github.com/newjersey/d4ad/pull/1909). A miscommunication removed the search query from the site title rather than fixing the `undefined`.
Now the page title should read `<query> | Advanced Search | Training Explorer | New Jersey Career Central` or, if no query, `Advanced Search | Training Explorer | New Jersey Career Central`.
=> 1510: Advanced Search title error - GA4

.github/workflows/dependabot-auto-approve-and-merge.yml
This commit refines the GitHub Actions workflow to automate the approval and merging process for Dependabot-generated pull requests targeting minor and patch updates. Key modifications include:
- Adjusting the trigger event to pull_request_target, ensuring the workflow runs securely in the context of the base repository.
- Incorporating a conditional step to approve only minor and patch updates, determined by the fetched PR metadata.
- Utilizing the GitHub CLI (`gh`) to execute approval and auto-merge commands seamlessly.
These changes streamline the integration of non-major version updates, enhancing the efficiency of dependency management while maintaining code stability and security.
=> Automate Dependabot PR approval and merge for minor/patch updates

frontend/src/components/AlertBar.tsx, frontend/src/components/Layout.tsx, frontend/src/utils/parseMarkdownToHTML.ts
Our application utilizes Markdown for content creation and presentation. Users have expressed a need for links within markdown content to open in new tabs to improve usability and retain the application context. Previously, links in markdown content opened in the same tab, potentially disrupting the user's workflow and navigation.
Objective:
To implement a solution that allows links within markdown-rendered content to open in new tabs by default, thereby enhancing the user experience by providing non-disruptive navigation. Additionally, address TypeScript related issues encountered during implementation to ensure type safety and maintainability.
Changes:
Enhanced Markdown Link Rendering:
Introduced parseMarkdownToHTMLWithLinksInNewTab function in src/utils/parseMarkdownToHtml.ts. This …
=> Enhance Markdown Rendering to Open Links in New Tabs

frontend/src/search-results/SearchResultsPage.tsx
Replace the regex lookbehind in SearchResultsPage with a compatible pattern to ensure the application functions correctly on all browsers, including older versions of Safari and Firefox. This change prevents the app from rendering a blank page due to unsupported regex features.
The updated regex captures the query parameter without using lookbehind assertions, thus improving compatibility and stability.
- Old regex: /(?<=\?q=).*?(?=&|$)/
- New regex: /\?q=([^&]*)/
=> Fix regex compatibility issue across browsers

frontend/src/components/HomeBanner.tsx, frontend/src/landing-page/LandingPage.tsx
This PR aims to optimize the Largest Contentful Paint (LCP) on the landing page by preloading the banner image in the `HomeBanner` component. This enhancement ensures faster loading times for the critical banner image, improving the overall user experience.
- **HomeBanner Component:**
- Added a `preload` prop to the `HomeBanner` component to enable preloading of the banner image.
- Included a `<link rel="preload" as="image" href={image.url} />` tag within the `HomeBanner` component to preload the banner image when the `preload` prop is true.
- **LandingPage Component:**
- Updated the `LandingPage` component to pass the `preload` prop to the `HomeBanner` component, ensuring the banner image is preloaded.
- **Improved Performance:** Preloading the banner image reduces the time it takes for …
=> Optimize LCP by Preloading Banner Image in HomeBanner Component

backend/src/database/data/PostgresDataClient.ts, backend/src/database/search/PostgresSearchClient.ts, backend/src/domain/search/searchTrainings.ts, backend/src/routes/router.ts
This PR addresses a specific issue where the "janitor" search query was not returning results due to incorrect program status filtering. Additionally, it improves the handling of blank search queries within the search logic.
1. **Resolve 'Janitor' Search Query Issue:**
- Added detailed logging to inspect `statusname` and `providerstatusname` fields before and after filtering.
- Ensured that only programs with a status of `APPROVED` are returned, while programs with a `Suspend` status are correctly excluded.
- Corrected TypeScript error instantiation by using `new Error()` to resolve compilation issues.
2. **Handle Blank Search Queries:**
- Implemented a check within the search logic to detect and handle blank or whitespace-only queries.
- Introduced a `BLANK_QUERY` error, which is caught …
=> [NJWE-2338] Fix Search Query Handling and Resolve 'Janitor' Search Issue

frontend/src/ApiClient.ts
This PR addresses the issue described in [NJWE-2344](https://fearless.jira.com/browse/NJWE-2344?atlOrigin=eyJpIjoiOTFhZjk1MTQ4ZmJkNGYwZjg1NWZjMjFlNjFhMjc5YWIiLCJwIjoiaiJ9), where search queries containing special characters, such as &, were being truncated when processed by the back end. The issue was traced to the query string not being URL-encoded before it was sent in the API request.
Changes:
Updated the getTrainingsByQuery method in ApiClient.ts to use encodeURIComponent on the search query string before appending it to the URL. This ensures that special characters are properly encoded and that the full query is processed by the server.
Testing:
Verified that search queries containing special characters, including &, are now correctly processed and return the expected results. …
=> Fix for NJWE-2344: Properly Encode Search Query to Handle Special Characters

backend/src/domain/search/searchTrainings.ts
This resolves [NJWE-2525](https://fearless.jira.com/browse/NJWE-2525)
=> cached unfiltered data and applied filter to the cached data of key "search-query"

backend/src/credentialengine/CredentialEngineUtils.ts, backend/src/domain/search/searchTrainings.ts, backend/src/domain/training/Training.ts, backend/src/domain/training/TrainingResult.ts, backend/src/domain/training/findTrainingsBy.ts, frontend/cypress/e2e/training-page.cy.js, frontend/src/domain/Training.ts, frontend/src/search-results/TrainingResultCard.tsx, frontend/src/training-page/TrainingPage.tsx
- Updated `getProviderData` in `CredentialEngineUtils.ts` to:
- Handle cases where `ceterms:ownedBy` is missing.
- Check for incomplete or invalid provider records (e.g., `{"errors":["Couldn't find Resource"]}`).
- Return `null` for missing providers with appropriate warnings.
- Adjusted `transformCertificateToTraining` in `searchTrainings.ts`:
- Added null checks for `provider`.
- Fallback to default values when `provider` is missing.
- Modified `findTrainingsBy.ts`:
- Ensured safe access to `provider` fields using null checks.
- Updated `Training` type to allow `provider` to be nullable.
- Enhanced TypeScript types:
- Updated `Training` and `Provider` interfaces to handle nullable `provider`.
- Frontend adjustments:
- Ensured components like `TrainingPage.tsx` and …
=> fix: Handle missing provider data gracefully across backend and frontend

frontend/package-lock.json, frontend/src/search-results/searchFunctions.ts
Fixes:
reporter: @mflymfly 
See screen capture: attached
Issue:
User searches "New Jersey" and gets results
User chooses a training
User goes back on browser
No results show / Term in search is now New+Jersey
[TE Bug - multi word search.webm](https://github.com/user-attachments/assets/31b2b5f6-b41f-47d0-8429-c856732fc1af)
This will also fix the problem of user seeing "+" in the search bar when refreshed or returned to search page
=> sending whitespace instead of "+" to search the entire query in the backend

backend/src/domain/training/findTrainingsBy.test.ts, backend/src/domain/training/findTrainingsBy.ts
- Updated `findTrainingsBy.ts` to return an empty array instead of throwing an error when no CE records are found.
- Added a test case in `findTrainingsBy.test.ts` to verify this behavior.
- Ensured the function fails gracefully and does not produce unhandled errors in logs.
Resolves NJWE-2639.
=> fix(training): handle missing CE records gracefully

frontend/src/locales/en.ts, frontend/src/locales/es.ts
resolves [NJWE-3108](https://fearless.jira.com/browse/NJWE-3108) and [NJWE-3107](https://fearless.jira.com/browse/NJWE-3107)
- updated the copy for training page banner
- updated the translation on the signup form
=> NJWE-3108 - sign up translations

backend/migrations/20250826180850-njwe-3328-cna-local-exception-updates.js, backend/migrations/sqls/20250826180850-njwe-3328-cna-local-exception-updates-down.sql, backend/migrations/sqls/20250826180850-njwe-3328-cna-local-exception-updates-up.sql
https://fearless.jira.com/browse/NJWE-3293
This PR implements the database migration to update local exception waivers for CNA/patient care aide programs following the 7/14 approval. The changes ensure that the correct CIP codes are applied to training programs in the specified counties.
On 7/14, approval was given for Atlantic, Camden, Cape May/Salem/Cumberland CNA/patient care aide in-demand waivers. The CIP code 51.3902 (Nursing Assistant/Aide and Patient Care Assistant/Aide) should be applied to all programs in these counties. Additionally, existing waivers for CIP code 51.2601 (Health Aide/LPNs) should be removed since LPNs are already demand occupations and don't need waivers.
**Additions:**
- Added CIP 51.3902 (Nursing Assistant/Aide and Patient Care Assistant/Aide) local exception …
=> [NJWE-3293] Add CNA/Patient Care Aide Local Exception Waivers Database Migration
