newjersey/dol-mcnj-main

- .github/workflows/codeql-analysis.yml
Summary
=======
Adds CodeQL weekly and on-PR static analysis scans to identify potential security issues as early as possible.
Test Plan
=======
PR serves as it's own test.
> chore: add CodeQL security scans

- frontend/src/components/Header.tsx
<a> must have className "link-format-black nav-item pvm phd bbdcg" to match the other elements
> Fixed counseling link className

- backend/src/careeronestop/CareerOneStopClient.test.ts
- backend/wiremock/mappings/career-onestop-web-developers.json
- frontend/cypress/e2e/in-demand-occupations-page.cy.js
- frontend/src/components/Header.tsx
- frontend/src/styles/header.scss
Implements header component from NJWDS + fix cypress, Wiremock test API request format issue as suggested by @namanaman alongside nav logo alignment fix from @derekkinsman 
* https://fearless.jira.com/browse/NJWE-54
* https://newjersey.github.io/njwds/components/detail/header--basic.html
* https://coforma.slack.com/archives/C043Q50JCRG/p1666283170636189
* Verify code doesn't throw lint, cypress, jest errors
* Perform visual comparison between to ensure changes are reflected as intended.
> UI Improvements: Nav bar updated to NJWDS component + Fix Wiremock for careeronestop - TE (NJWE-54)

- backend/migrations/20221115205311-update-etpl.js
- backend/migrations/sqls/20221115205311-update-etpl-down-TEST.sql
- backend/migrations/sqls/20221115205311-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2022-11-15
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2022-11-15.
> chore: update ETPL data as of 2022-11-15

- backend/migrations/20221122234345-update-etpl.js
- backend/migrations/sqls/20221122234345-update-etpl-down-TEST.sql
- backend/migrations/sqls/20221122234345-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2022-11-22
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2022-11-22.
> chore: update ETPL data as of 2022-11-22

- backend/migrations/20221202234337-update-etpl.js
- backend/migrations/sqls/20221202234337-update-etpl-down-TEST.sql
- backend/migrations/sqls/20221202234337-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2022-12-02
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2022-12-02.
> chore: update ETPL data as of 2022-12-02

- backend/migrations/20221219225633-update-etpl.js
- backend/migrations/sqls/20221219225633-update-etpl-down-TEST.sql
- backend/migrations/sqls/20221219225633-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2022-12-19
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2022-12-19.
> chore: update ETPL data as of 2022-12-19

- frontend/package.json
https://github.com/axios/axios/issues/5026 🤞
> axios fix (maybe)

- backend/migrations/20230110171313-update-etpl.js
- backend/migrations/sqls/20230110171313-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230110171313-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-01-10
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-01-10.
> chore: update ETPL data as of 2023-01-10

- backend/migrations/20230201194704-update-etpl.js
- backend/migrations/sqls/20230201194704-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230201194704-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-01-31
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-01-31.
> chore: update ETPL data as of 2023-01-31

- backend/migrations/20230208194230-update-etpl.js
- backend/migrations/sqls/20230208194230-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230208194230-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-02-08
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-02-08.
> update ETPL data as of 2023-02-08

- backend/migrations/20230213223546-update-etpl.js
- backend/migrations/sqls/20230213223546-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230213223546-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-02-13
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-02-13.
> chore: update ETPL data as of 2023-02-13

- backend/migrations/20230301005305-update-etpl.js
- backend/migrations/sqls/20230301005305-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230301005305-update-etpl-up-TEST.sql
- frontend/cypress/e2e/training-page.cy.js
Summary
=======
- Updates the ETPL data as of 2023-02-27
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-02-27.
> chore: update ETPL data as of 2023-02-27

- backend/migrations/20230403182129-update-etpl.js
- backend/migrations/sqls/20230403182129-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230403182129-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-04-03
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-04-03.
> chore: update ETPL data as of 2023-04-03

- backend/data/csvDeleteAllAndInsert.js
- backend/migrations/20230406193153-update-etpl.js
- backend/migrations/sqls/20230406193153-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230406193153-update-etpl-up-TEST.sql
Enable search by provider name
https://fearless.jira.com/browse/NJWE-522
> enable search by provider name

- backend/migrations/20230410180727-update-etpl.js
- backend/migrations/sqls/20230410180727-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230410180727-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-04-10
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-04-10.
> chore: update ETPL data as of 2023-04-10

- frontend/cypress/e2e/search.cy.js
comment out problematic accessibility check in "searches from the search results page"
> comment out problematic accessibility check

- backend/migrations/20230418155940-update-etpl.js
- backend/migrations/sqls/20230418155940-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230418155940-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-04-18
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-04-18.
> seeded 2023-04-18 data

- .circleci/config.yml
> Revert "test build"

- backend/migrations/20230504193237-update-etpl.js
- backend/migrations/sqls/20230504193237-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230504193237-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-04-24
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-04-24.
> seeded etpl data 2023-04-24

- backend/migrations/20230505194821-update-etpl.js
- backend/migrations/sqls/20230505194821-update-etpl-down-TEST.sql
- backend/migrations/sqls/20230505194821-update-etpl-up-TEST.sql
Summary
=======
- Updates the ETPL data as of 2023-05-05
Test Plan
=========
- Ran through the seed guide using latest ETPL data as of 2023-05-05.
> seeded etpl data 2023-05-05

- .circleci/config.yml
- Enhance step labels for better readability and understanding.
- Add descriptive names to frontend and backend testing steps.
> refactor: Improve clarity of CircleCI workflow step labels

- frontend/cypress/e2e/home-page.cy.js
- frontend/src/components/CardSlider.tsx
- frontend/src/landing-page/LandingPage.tsx
hid those blocks! for [NJWE-1178](https://fearless.jira.com/browse/NJWE-1178) and [NJWE-1179](https://fearless.jira.com/browse/NJWE-1179)
> hiding career pathways

- frontend/src/components/InDemandBlock.tsx
- frontend/src/components/SearchBlock.tsx
- frontend/src/faq-page/FaqPage.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/queries/trainingExplorer.ts
- frontend/src/styles/components/_search-block.scss
- frontend/src/styles/index.scss
- frontend/src/styles/pages/_search-results-page.scss
- frontend/src/training-explorer-page/TrainingExplorerPage.tsx
- frontend/src/training-page/TrainingPage.tsx
- frontend/src/types/contentful.ts
closes [NJWE-1154](https://fearless.jira.com/browse/NJWE-1154), [NJWE-1198](https://fearless.jira.com/browse/NJWE-1198), and [NJWE-1215](https://fearless.jira.com/browse/NJWE-1215)
- added a drawer to the training explore for a SOC code definition
- fixed the CTA on the FAQ page
- fixed the underline on the occupation and training pages
> Scott - NJWE-1154, NJWE-1198, NJWE-1215, and NJWE-1210

- frontend/cypress/e2e/navigation_paths.js
- frontend/src/components/HomeBanner.tsx
- frontend/src/components/IndustryBlock.tsx
- frontend/src/components/River.tsx
- frontend/src/queries/careerNavigator.ts
- frontend/src/queries/homePage.ts
- frontend/src/queries/trainingProvider.ts
- frontend/src/queries/tuitionAssistance.ts
- frontend/src/types/contentful.ts
Closes [NJWE-1246](https://fearless.jira.com/browse/NJWE-1246)
> description for alt tags

- frontend/public/index.html
added a condition in the `index.html` file that injects the google tag manager script so that if it's on the `d4ad-research` staging site, it will add the new tag manager for testing
> Google tag test in staging

- frontend/cypress/e2e/paths.js
- frontend/public/index.html
all tests seem to pass on the last PR but failed when trying to deploy. This fix seemed to be the reason. Hopefully we're all good after this.
> Fixing a bug in feature tests

- frontend/cypress/e2e/navigation_paths.js
- frontend/src/components/Layout.tsx
- frontend/src/components/modules/NavMenu.tsx
- frontend/src/components/modules/NavSubMenu.tsx
closes [NJWE-1252](https://fearless.jira.com/browse/NJWE-1252) and [NJWE-1248](https://fearless.jira.com/browse/NJWE-1248)
- changed nav to the new nav in the query
- fixed the bug so that only one dropdown opens at a time
- also changed an item in `navigation_paths.js` to fix an error in Circle CI
> Updated Nav

- frontend/public/index.html
Adding in google tag manager for "https://d4ad-research2.uk.r.appspot.com/"
> Google tag manager for "research2"

- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/career-navigator-page/CareerNavigatorPage.tsx
- frontend/src/career-pathways-page/CareerPathwaysPage.tsx
- frontend/src/components/HowTo.tsx
- frontend/src/components/IntroBlocks.tsx
- frontend/src/components/Layout.tsx
- frontend/src/components/OccupationBlock.tsx
- frontend/src/components/PageBanner.tsx
- frontend/src/components/Stepper.tsx
- frontend/src/components/modules/RelatedTrainingSearch.tsx
- frontend/src/fence.json
- frontend/src/filtering/FilterBox.tsx
- frontend/src/landing-page/LandingPage.tsx
- frontend/src/search-results/SearchResultsPage.tsx
- frontend/src/styles/components/_how-to.scss
- frontend/src/styles/components/_interrupter.scss
- frontend/src/styles/components/_introBlocks.scss
- frontend/src/styles/components/_page-banner.scss
- frontend/src/styles/components/_stepper.scss
- frontend/src/styles/index.scss
- frontend/src/styles/modules/_backToTop.scss
- frontend/src/styles/modules/_cta.scss
- frontend/src/styles/pages/_landing-page.scss
- frontend/src/styles/pages/_training-explorer.scss
- frontend/src/styles/variables.scss
- frontend/src/training-explorer-page/TrainingExplorerPage.tsx
- frontend/src/utils/parseMarkdownToHTML.ts
Closes [NJWE-1319](https://fearless.jira.com/browse/NJWE-1319), [NJWE-1320](https://fearless.jira.com/browse/NJWE-1320), [NJWE-1322](https://fearless.jira.com/browse/NJWE-1322), and [NJWE-1323](https://fearless.jira.com/browse/NJWE-1323)
- added the blocks back onto the homepage under the banner
- pulling in the correct navigation menu in the header
- ported all the 2.1 style fixes from a previous PR
- fixed the markdown that is being used on some of the icon cards
This also seems to take care of [NJWE-1230](https://fearless.jira.com/browse/NJWE-1230)
> NJWE-1273 - Review 1.0 Staging

- frontend/src/components/SearchBlock.tsx
This fixes [NJWE-1299](https://fearless.jira.com/browse/NJWE-1299)
> TE - Search submit bug

- frontend/cypress/e2e/filtering-and-sorting.cy.js
- frontend/cypress/e2e/navigation_paths.js
- frontend/cypress/e2e/search.cy.js
- frontend/src/App.tsx
- frontend/src/components/SearchBlock.tsx
- frontend/src/filtering/FilterBox.tsx
https://fearless.jira.com/browse/NJWE-1405
> [NJWE-1405] Modify TE search path from /search to /training/search

- frontend/src/components/OccupationBlock.tsx
- frontend/src/error/NotFoundPage.tsx
- frontend/src/search-results/SearchResultsPage.tsx
Resolves [1436](https://fearless.jira.com/jira/software/projects/NJWE/boards/114?assignee=712020%3A7f5e8498-eeba-4ef6-b44a-4185883e207e&selectedIssue=NJWE-1436) & [1437](https://fearless.jira.com/jira/software/projects/NJWE/boards/114?assignee=712020%3A7f5e8498-eeba-4ef6-b44a-4185883e207e&selectedIssue=NJWE-1437)
Fix broken/wrong links.
> 1436 & 1437: Update links.

- backend/src/routes/emailRoutes.ts
- frontend/src/components/UpdateNotifier.tsx
Resolves [NJWE-1568](https://fearless.jira.com/browse/NJWE-1568)
- removed some logic that checks both fields so that it only checks the email
> NJWE-1568 - Update Notifier error bug fix

- backend/src/app.ts
- frontend/.eslintrc.json
- frontend/cypress/e2e/image-svg.cy.js
- frontend/cypress/e2e/navigation_paths.js
- frontend/src/components/SearchBlock.test.tsx
- frontend/src/components/__tests__/StatBlock.test.tsx
- frontend/src/search-results/__tests__/TrainingResultCard.test.tsx
- frontend/tsconfig.json
- scripts/test-all.sh
This PR introduces a series of enhancements aimed at improving the accuracy of test reporting within our project. Significant changes include the update of CircleCI scripts to ensure Jest test errors are appropriately flagged, adjustments to maintain ESLint compliance, and updates to configuration files like .eslintrc.json and tsconfig.json to bolster code quality. These modifications are part of our ongoing efforts to ensure the reliability and maintainability of our codebase.
> Report accurate tests

- backend/src/app.ts
This Pull Request introduces changes to the server configuration to allow the Career Navigator application to successfully connect with the My Career NJ API. By configuring the Cross-Origin Resource Sharing (CORS) middleware with specific options, we enable seamless interaction between the frontend of Career Navigator and our main backend services. This is a crucial step in ensuring that users of the Career Navigator can access the resources and functionalities provided by the My Career NJ API without encountering cross-origin request issues.
- Primary Goal: To allow the Career Navigator application to connect to the My Career NJ API.
To ensure secure communication between different origins by restricting API access to trusted sources.
To support the development environment by allowing …
> Enable CORS for Career Navigator to Access My Career NJ API

- frontend/src/components/AlertBar.tsx
- frontend/src/components/Layout.tsx
- frontend/src/components/ResourceList.tsx
- frontend/src/components/__tests__/AlertBar.test.tsx
- frontend/src/styles/global/_globalHeader.scss
Resolves [NJWE-1687](https://fearless.jira.com/browse/NJWE-1687)
- Created a reusable component for Alerts
- replaced it on the `ResourceCategoryPage`
- added it to the Layout with a dismissible button
- created a test for AlertBar component
- put it all behind a feature flag
> NJWE-1687 - Maintenance Warning Banner

- frontend/src/components/Layout.tsx
> update maintenance banner text

- frontend/src/career-navigator-page/CareerNavigatorPage.tsx
- frontend/src/career-pathways-page/CareerPathwaysPage.tsx
- frontend/src/components/CareerDetail.tsx
- frontend/src/components/CareerPathways.tsx
- frontend/src/components/IndustryBlock.tsx
- frontend/src/components/IndustrySelector.tsx
- frontend/src/components/OccupationBlock.tsx
- frontend/src/components/PageBanner.tsx
- frontend/src/components/ResourceList.tsx
- frontend/src/styles/components/_ctaBanner.scss
- frontend/src/styles/components/_homeBanner.scss
- frontend/src/styles/components/_resource-filter.scss
- frontend/src/styles/components/_search-block.scss
- frontend/src/styles/global/_footer.scss
- frontend/src/styles/global/_globalHeader.scss
- frontend/src/styles/global/_header.scss
- frontend/src/styles/global/_subFooter.scss
- frontend/src/styles/index.scss
- frontend/src/styles/pages/_home-page.scss
- frontend/src/styles/system.scss
Resolves [NJWE-1573](https://fearless.jira.com/browse/NJWE-1573)
- Made all contained things, using the `.container` class 1300px wide
- removed the `.plus` modifier class
- added a new screen width scss variable `$desktop-xl`
> NJWE-1573 - Global Widths

- frontend/src/components/SearchBlock.tsx
- frontend/src/filtering/FilterBox.tsx
- frontend/src/search-results/SearchResultsPage.tsx
- frontend/src/search-results/__tests__/SearchResultsPage.test.tsx
Resolves - [NJWE-1781](https://fearless.jira.com/browse/NJWE-1781)
- added a regex to extract the search params
-  [x] Design review
-  [ ] Dev Review
> BUG - NJWE-1781 

- frontend/cypress/e2e/search.cy.js
- frontend/cypress/support/commands.js
- frontend/src/components/SearchBlock.tsx
This Pull Request introduces targeted enhancements to the search functionality of our application, specifically aimed at improving how ampersands (`&`) are handled within search queries. The update ensures that search inputs containing ampersands are correctly interpreted and processed, enhancing the accuracy of search results and the overall user experience.
- **Improved Ampersand Handling**: Implemented adjustments in the search box's input processing logic to ensure that ampersands are correctly encoded and interpreted by our search processing backend. This change allows users to search for terms that include ampersands, reflecting real-world search scenarios more accurately.
- **Enhanced Input Sanitization**: Strengthened input sanitization measures for search queries to include …
> [NJWE-1822] Improve Handling of Ampersands in Training Explorer Search Queries

- backend/src/app.ts
- backend/src/credentialengine/CredentialEngineAPI.ts
- backend/src/database/data/PostgresDataClient.ts
- backend/src/domain/occupations/getOccupationDetail.test.ts
- backend/src/domain/occupations/getOccupationDetail.ts
- backend/src/domain/occupations/getOccupationDetailByCIP.ts
- backend/src/domain/search/searchTrainings.ts
- backend/src/domain/test-objects/factories.ts
- backend/src/domain/training/Training.ts
- backend/src/domain/training/TrainingResult.ts
- backend/src/domain/training/convertTrainingToTrainingResult.ts
- backend/src/routes/router.ts
- frontend/src/occupation-page/OccupationPage.tsx
- frontend/src/search-results/TrainingResultCard.tsx
[1810](https://fearless.jira.com/browse/NJWE-1810)
[1779](https://fearless.jira.com/browse/NJWE-1779)
> added related trainings to occupation page

- backend/migrations/20240423232443-update-etpl.js
- backend/migrations/sqls/20240423232443-update-etpl-down-TEST.sql
- backend/migrations/sqls/20240423232443-update-etpl-up-TEST.sql
Artifact of https://fearless.jira.com/browse/NJWE-1851?atlOrigin=eyJpIjoiMjZjZjE2MGNkZGNjNDJkNThiOWQ4YTAxYzI3NDBjOTQiLCJwIjoiaiJ9
> [NJWE-1851] remove etpl abbreviations handling for provider field

- backend/src/credentialengine/CredentialEngineUtils.ts
- backend/src/domain/training/findTrainingsBy.ts
https://fearless.jira.com/browse/NJWE-1122?atlOrigin=eyJpIjoiNmZhNjBmNGFmMTUxNDM0MGJkYWI0ODZlMDFkYjZjNjIiLCJwIjoiaiJ9
> [NJWE-1122] evening courses

- backend/src/domain/training/findTrainingsBy.ts
- backend/src/domain/utils/validateCtId.ts
- backend/src/routes/router.ts
[NJWE-1866](https://fearless.jira.com/browse/NJWE-1866)
> Prevent users from being able to view non-NJDOL programs using TrainingPage

- frontend/src/styles/global/_footer.scss
- frontend/src/styles/global/_header.scss
- frontend/src/styles/global/_subFooter.scss
- frontend/src/styles/pages/_home-page.scss
> Optimized Cumulative Layout Shift (CLS) metric 

- frontend/public/index.html
- frontend/src/training-page/TrainingPage.tsx
This PR enhances the HTML metadata and SEO attributes of the My Career NJ website. The changes aim to improve the site's visibility on search engines, enhance social media sharing, and provide a better user experience. The following updates have been made:
1. **Meta Description**:
- Updated to provide a more detailed overview of the site's offerings: "Find job training, career resources, and employment opportunities in New Jersey with the New Jersey Department of Labor."
2. **Meta Keywords**:
- Added keywords to improve search engine optimization: "job training, career resources, employment opportunities, Bergen County, Essex County, Camden County, NJ, New Jersey."
3. **Title Tag**:
- Added a title tag for better accessibility and SEO: `<title>My Career NJ</title>`.
4. **Open Graph …
> Update HTML Metadata and Enhance SEO - 2024-05-21

- frontend/src/components/StatBlock.tsx
- frontend/src/occupation-page/OccupationPage.tsx
- frontend/src/training-page/TrainingPage.tsx
[NJWE-2330](https://fearless.jira.com/browse/NJWE-2330)
> fixed the undefined * and removed * from Datasource

- backend/src/domain/search/searchTrainings.ts
This PR introduces significant improvements to the caching mechanism used in the training search functionality. The key changes include:
- **Background Page Caching**: After a user loads a page, the next two pages are fetched and cached in the background, ensuring a smoother user experience when navigating through results.
- **Immediate Cache Check**: On every new page load, the system first checks the cache for available data before attempting to fetch new results, reducing unnecessary API calls and improving response time.
- **Code Simplification**: The fetching logic was streamlined to ensure that caching is handled consistently, and redundant code was removed.
- **Detailed Logging**: Added comprehensive logging throughout the caching and fetching processes to make debugging easier and …
> [Credential Engine] Enhance Caching Mechanism for Training Search Results

- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/search-results/Pagination.tsx
- frontend/src/search-results/ResultsHeader.tsx
- frontend/src/search-results/SearchResultsPage.tsx
- frontend/src/search-results/SkeletonCard.tsx
- frontend/src/search-results/searchFunctions.ts
Resolves [NJWE-2334](https://fearless.jira.com/browse/NJWE-2334)
- Replaced the spinning loading circle icon with a "skeleton" of the result card for better user feed back
> NJWE 2334 - loading screen

- frontend/src/components/HomeBanner.tsx
- frontend/src/components/TrainingExplorerHeading.tsx
- frontend/src/landing-page/LandingPage.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/styles/components/_homeBanner.scss
- frontend/src/styles/pages/_training-explorer.scss
Resolves [NJWE-2364](https://fearless.jira.com/browse/NJWE-2364) & [NJWE-2362](https://fearless.jira.com/browse/NJWE-2362)
- Added subheading copy to the home page and training explorer
> landing page copy

- frontend/src/search-results/Pagination.tsx
Resolves - [NJWE-2353](https://fearless.jira.com/browse/NJWE-2353)
- added a line that takes the user back to the top of the page when clicking on a page number button
> Pagination - scroll to top on change

- frontend/src/components/CardRow.tsx
- frontend/src/components/CareerDetail.tsx
- frontend/src/components/IntroBlocks.tsx
- frontend/src/components/OccupationBlock.tsx
- frontend/src/landing-page/LandingPage.tsx
- frontend/src/styles/components/_introBlocks.scss
Resolves [NJWE-2421](https://fearless.jira.com/browse/NJWE-2421), [NJWE-2425](https://fearless.jira.com/browse/NJWE-2425), & [NJWE-2426](https://fearless.jira.com/browse/NJWE-2426)
- Added the card row onto the homepage that contains Career Pathways
- Made sure that the tool tips were working on Healthcare and TDL occupation sections
- Added content into Contentful that will be visible after the launch of Career Pathways in the navbar and homepage
> Career pathways updates

- backend/data/transform-for-career-navigator/transform-for-career-navigator.py
[NJWE-2464](https://fearless.jira.com/browse/NJWE-2464)
> [NJWE-2464] - fixed transform for navigator to include trainings with approved providers only

- backend/package-lock.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/error/TempNotFound.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/training-page/TrainingPageRouter.tsx
resolves [NJWE-2500](https://fearless.jira.com/browse/NJWE-2500)
- create a new routing component that looks for a program ID so it gives the proper Error Message
Example image of a made up path `/training/23224`
> temp not found

- frontend/src/components/AlertBar.tsx
- frontend/src/components/Layout.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/search-results/SearchTips.tsx
- frontend/src/styles/components/_alertBar.scss
- frontend/src/styles/global/_globalHeader.scss
- frontend/src/styles/index.scss
resolves [NJWE-2493](https://fearless.jira.com/browse/NJWE-2493)
- replaced the copy that was in place for a small amount of results with an AlertBox component with a toggle
> NJWE-2493 - not seeing results

- backend/src/domain/search/searchTrainings.ts
[NJWE-2582](https://fearless.jira.com/browse/NJWE-2582)
> implemented support services filter

- backend/src/contentful/client.ts
- backend/src/utils/secretManager.ts
Also handles switching api keys on aws secrets manger
> change contentful environment based on ENV provided in .env file

- frontend/src/components/Header.tsx
This PR will dynamically show/hide signup form based on the flag on the env vars
Testing:
Add a **REACT_APP_SIGNUP_FOR_UPDATES** variable to your list of environment variables and set it to true to show and set it to false to hide
For now:
I will set it up to false in PROD
and true in DEV and TEST Env
> added feature flag for signup forms

- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/styles/global/_header.scss
resolves [NJWE-2703](https://fearless.jira.com/browse/NJWE-2703), [NJWE-2707](https://fearless.jira.com/browse/NJWE-2707), [NJWE-2708](https://fearless.jira.com/browse/NJWE-2708), [NJWE-2709](https://fearless.jira.com/browse/NJWE-2709), and [NJWE-2706](https://fearless.jira.com/browse/NJWE-2706)
- NJWE-2703 Updated the Success Message
- NJWE-2707 capitalize mobile phone number
- NJWE-2708 link font size fix
- NJWE-2709 added hyphen
- NJWE-2706 removed hyphen
> User Sign-up Form content updates

- backend/src/controllers/contactController.test.ts
- backend/src/controllers/contactController.ts
- frontend/cypress/e2e/career-support-page.cy.js
- frontend/cypress/e2e/contact-us-page.cy.js
- frontend/src/components/Header.tsx
- frontend/src/contact-us-page/ContactForm.tsx
Auto select career-navigator topic and added topic to be include in subject as well
This PR includes [NJWE-2410](https://fearless.jira.com/browse/NJWE-2410)
> NJWE-2410 

- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
resolves [NJWE-2777](https://fearless.jira.com/browse/NJWE-2777)
- updated the form description
> NJWE-2777-form description-update

- frontend/src/styles/modules/_iconCard.scss
resolves [NJWE-2794](https://fearless.jira.com/browse/NJWE-2794)
- added hover state to category cards on the homepage
> NJWE-2794 - card hover state

- frontend/src/career-pathways-page/CareerPathwaysPage.tsx
- frontend/src/career-pathways-page/content.ts
- frontend/src/components/PageBanner.tsx
- frontend/src/contact-us-page/ContactUsPage.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
- frontend/src/styles/pages/_career-pathways.scss
- frontend/src/types/contentful.ts
- Updated copy as per requested
> Copy Change Requests

- frontend/src/styles/global/_footer.scss
resolves [NJWE-2473](https://fearless.jira.com/browse/NJWE-2473)
- increased the padding around links in the footer for easier ability to touch the desired link
> NJWE-2473 - Footer touch link space

- frontend/src/in-demand-occupations-page/InDemandOccupationsPage.tsx
- frontend/src/locales/en.ts
- frontend/src/locales/es.ts
resolves [NJWE-3090](https://fearless.jira.com/browse/NJWE-3090)
- updated banner copy for the `main` branch
> copy update for in demand page

- frontend/src/components/SignUpFormModal.tsx
> Bold button

- README.md
This PR completely overhauls the README.md file to provide comprehensive, professional documentation for the My Career NJ project. The update addresses all identified issues with outdated information, broken links, and incomplete documentation while significantly enhancing the user experience for developers, contributors, and users.
- Added professional header with emoji, tagline, and comprehensive badge collection
- Expanded project description to clearly explain the platform's purpose and scope
- Added mission statement and New Jersey Department of Labor context
- Documented key features with detailed explanations
- **Table of Contents**: Added comprehensive navigation
- **Getting Started**: Enhanced with prerequisites, version requirements, verification steps, and troubleshooting
- …
> Comprehensive README.md update with enhanced documentation

- backend/src/app.ts
Potential fix for [https://github.com/ChelseaKR/dol-mcnj-main/security/code-scanning/1](https://github.com/ChelseaKR/dol-mcnj-main/security/code-scanning/1)
To properly fix the issue, rate limiting should be introduced for the route handlers that serve files from the filesystem (the `/` and `*` endpoints, as well as potentially others where `res.sendFile` or similar IO occurs). The recommended approach is to use the well-established `express-rate-limit` middleware package. This involves importing the package, configuring a sensible rate limiter (e.g., X requests per Y minutes), and applying it directly to the vulnerable endpoints. To avoid changing unrelated functionality, the middleware should be inserted just before the route handlers for `/` and `*`. Required changes include: importing …
> Potential fix for code scanning alert no. 1: Missing rate limiting
